[project]
name = "adaptive-server-routing-bandit"
version = "0.1.0"
description = ""
authors = [
    {name = "ignius299792458"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy (>=2.5.3,<3.0.0)",
    "pandas (>=3.0.6,<4.0.0)",
    "matplotlib (>=3.11.2,<4.0.0)"
]

[tool.poetry]
packages = [{include = "adaptive_routing", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "ruff (>=0.16.8,<0.17.0)"
]
